### PR TITLE
Add initial concourse worker dashboard.

### PR DESCRIPTION
**Pull request by jmcarp**
Added a very basic concourse worker dashboard using the influx exporter to ship metrics from concourse. I still need to verify that this works with the `prometheus-dashboards` script, but so far it looks like this:

screen shot 2017-06-20 at 12 22 22 am

cc @LinuxBozo @dlapiduz

### CODE REVIEW

**Comment by mkuratczyk** [comment]
Thanks for starting this. I hope to migrate dashboards from https://metrics.concourse.ci to Prometheus but so far I've been trying to migrate the Builds dashboard and I'm still struggling how to do that. Problem is these are events and Prometheus is not great at handling that. Any ideas welcome. :)

**Comment by dlapiduz** [comment]
@jmcarp I don't want to be greedy but is there a chance that you can add some docs or point us to how you did the influx/concourse integration?

**Comment by jmcarp** [comment]
* Run the `influxdb_exporter` on prometheus
* Point the concourse influxdb sink to it: https://github.com/concourse/concourse/blob/master/jobs/atc/spec#L392-L411

@dlapiduz

**Comment by jmcarp** [comment]
screen shot 2017-07-03 at 7 27 50 pm

I added a few more panels and some basic templating. We should be able to recreate other panels from metrics.concourse.ci using metrics from the bosh health monitor or node exporter in the future--concourse gets those metrics from riemann-health, but most users of this release will already have other sources of system metrics.

I'm not sure what to do with concourse data that are events and not metrics.

**Comment by jmcarp** [comment]
I'm removing the `[WIP]`, since I think this is good enough to be useful even though it doesn't have everything from metrics.concourse.ci.

**Pull request merged**
