### PR TITLE
add UAA parameters to bosh_exporter_ctl

### PR DESCRIPTION
**Pull request by mkuratczyk**
Added UAA parameters to bosh_exporter_ctl (to allow setting them through a manifest)

### CODE REVIEW

**Comment by frodenas** [comment]
Nice catch, thanks @mkuratczyk!

**Comment by mkuratczyk** [comment]
Would you mind releasing a new version with the fix? I just got a question from another person who ran into this issue. :) Thanks a lot

**Comment by frodenas** [comment]
Sure, I need to cut a new bosh_exporter version with the https://github.com/cloudfoundry-community/bosh_exporter/issues/1 fix and I will create a new final release.

**Comment by frodenas** [comment]
I mean https://github.com/cloudfoundry-community/bosh_exporter/issues/2.

**Comment by frodenas** [comment]
[Prometheus BOSH release v11](http://bosh.io/releases/github.com/cloudfoundry-community/prometheus-boshrelease?version=11)

**Pull request merged**
