### PR TITLE
add multi user support for nginx basic auth

### PR DESCRIPTION
**Pull request by ionphractal**
This change adds the possibility to configure optional additional auth_users array for each of the 3 frontend services. I designed it not to break present setups or other internal uses of auth_username/auth_password. Looking forward to your feedback.

### CODE REVIEW

**Comment by frodenas** [comment]
Hey @ionphractal, thanks for the PR. Two comments:

1. The next release has some [breaking changes](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/ci/release_notes.md#breaking-changes), so this is a good moment to introduce more changes. Having two different properties to add users is confusing, I'd prefer to have a single property, so let's use the new `auth_users` array and remove the old `auth_username` and `auth_password` properties.

2. The ctl script is starting to have more logic than desired, so I'd like to move the user creation steps to a `pre-start` script. If you know how to do it, can you please create a `pre-start` script and move the user creation logic into it. If you don't know how to do it, no worries, I will merge this PR and I will refactor it later.

Thanks.

**Comment by ionphractal** [comment]
Hi @frodenas , thanks for your feedback. That is indeed a great opportunity for some more breaking changes. As for the `pre-start` script I won't get it done this week and I'm on vacation next week. If that's ok for you I'll do it afterwards. In case you'd get it done by then, that's fine for me, too.

**Comment by frodenas** [comment]
@ionphractal No problem, just update the properties and we will do the `pre-start` script later. Thanks!

**Comment by frodenas** [comment]
Hey @ionphractal, are you still working on this?

**Comment by ionphractal** [comment]
Hi @frodenas , sorry I didn't find the time to work on it yet. Hope to find it later this week.

**Comment by ionphractal** [comment]
Hey @frodenas, when I tested my recent commit, I noticed that Grafana doesn't differenciate between basic auth user and it's own which basically means one has to fill in both, the nginx auth_users and grafana.security.admin_user/grafana.users.seeded_global_user, with the same data. That's kind of not dry but I wasn't able to come up with a solution for it. Do you have any idea?

**Comment by frodenas** [comment]
@ionphractal I don't tend to set a basic auth for grafana (only for prometheus and alertmanager).

**Comment by ionphractal** [comment]
@frodenas I see. Well it's more a cosmetic thing anyway, so let's put that aside for now. Have you had a chance to test the code yet?

**Pull request merged**
