### PR TITLE
Add a new dashboard: system overview linked to bosh

### PR DESCRIPTION
**Pull request by ArthurHlt**
This dashboard give the possibility to user to target a bosh's VM which have node_exporter by choosing deployment and job from a bosh.

More understanding screenshot:
capture d ecran 2017-01-18 a 14 11 25

In the same time I've reworked queries on panels for all systems dashboard to be more permissive to find from a host  (e.g.: query ` node_load1{instance="$host"}` become `node_load1{instance=~"$host(:[0-9]+)?"}` )
And in `templating` of each systems dashboard, we don't see anymore the port associated to an ip (it was just to prettify).

### CODE REVIEW

**Comment by jhiemer** [comment]
@ArthurHlt this is a very nice enhancement. I have currently the problem, when deploying the node_exporter to all existing bosh deployments via

`bosh update runtime-config runtime.yml`

and 

```yml
releases:
- name: prometheus
  version: 12.3.3

addons:
- name: node_exporter_1
  jobs:
  - name: node_exporter
    release: prometheus

```

that it works, except for the prometheus release, with the following error:

```shell
Error 100: Unable to render instance groups for deployment. Errors are:
   - File exists @ dir_s_mkdir - /tmp/d20170117-30731-16lldu1/node_exporter
```

This is not related to your pull request, but as I am currently trying to document a reference setup it would be nice if you could give me a short reply if you experience the same, or not.

**Comment by ArthurHlt** [comment]
@jhiemer thank you :) 
I think it would be better to create a dedicated issue next time. This is for next person who might search for the same issue.

I didn't had this issue, but by 2 cents:
- first be sure that in your deployment you don't have node_exporter already inside your prometheus manifest (normally when trying to deploy bosh should complains about it)
- it might be cause you had before the job node_exporter in your deployment, try to do `bosh deploy --recreate` to have clean vms cause it's actually look like it's just blocking cause a mkdir failed.

**Comment by cppforlife** [comment]
btw i believe also that this error msg was improved in 260.x bosh release.

**Comment by jhiemer** [comment]
@ArthurHlt yes you right. So I have tried your dashboard an it works quite fine. 

Question: based on those node_exporter rules it would make sense to have alarm definitions as well, what do you think?

@cppforlife thanks for the hint regarding bosh.

**Comment by ArthurHlt** [comment]
@jhiemer Yes definitely we need alarms on this

**Comment by frodenas** [comment]
Thanks @ArthurHlt!

@jhiemer To deal with the `File exists @ dir_s_mkdir` error, I've just created a standalone [node-exporter-boshrelease](https://github.com/cloudfoundry-community/node-exporter-boshrelease). This will be useful when you deploy the `node_exporter` as a BOSH Addon. Bear in mind, that I still need to remove the `node_exporter` from this BOSH release and cut a new final release.

**Comment by jhiemer** [comment]
@frodenas yep, thanks!

**Comment by ArthurHlt** [comment]
@frodenas yes I saw that, that's a great move. thank you .

**Pull request merged**
